#ifndef VERSION_H
#define VERSION_H

#define VERSION_MAJOR		0
#define VERSION_MINOR		1
#define VERSION_MICRO		1
#define VERSION_RELEASELEVEL	("final")
#define VERSION_SERIAL		0

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define VERSION TOSTRING(VERSION_MAJOR) "." \
	TOSTRING(VERSION_MINOR) "." \
	TOSTRING(VERSION_MICRO)

#endif // VERSION_H
